package com.framework.entity;
// Generated 2017-5-27 22:17:08 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * SysMenu generated by hbm2java
 */
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler" })
@Entity
@Table(name = "sys_menu", catalog = "wx")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE, region = "com.framework.entity.SysMenu")
public class SysMenu implements java.io.Serializable {

	private int id;
	private String category;
	private String name;
	private String url;
	private Integer parentId;
	private Integer flag;
	private String target;
	private String description;
	private Set<SysMenuClass> sysMenuClasses = new HashSet<SysMenuClass>(0);
	private Set<SysRolePermission> sysRolePermissions = new HashSet<SysRolePermission>(0);

	public SysMenu() {
	}

	public SysMenu(int id) {
		this.id = id;
	}

	public SysMenu(int id, String category, String name, String url, Integer parentId, Integer flag, String target,
			String description, Set<SysMenuClass> sysMenuClasses, Set<SysRolePermission> sysRolePermissions) {
		this.id = id;
		this.category = category;
		this.name = name;
		this.url = url;
		this.parentId = parentId;
		this.flag = flag;
		this.target = target;
		this.description = description;
		this.sysMenuClasses = sysMenuClasses;
		this.sysRolePermissions = sysRolePermissions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "category", length = 50)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", length = 45)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "flag")
	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	@Column(name = "target", length = 32)
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysMenu")
	public Set<SysMenuClass> getSysMenuClasses() {
		return this.sysMenuClasses;
	}

	public void setSysMenuClasses(Set<SysMenuClass> sysMenuClasses) {
		this.sysMenuClasses = sysMenuClasses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysMenu")
	public Set<SysRolePermission> getSysRolePermissions() {
		return this.sysRolePermissions;
	}

	public void setSysRolePermissions(Set<SysRolePermission> sysRolePermissions) {
		this.sysRolePermissions = sysRolePermissions;
	}

}
