package com.framework.entity;
// Generated 2017-5-25 22:34:35 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * SysRolePermissionId generated by hbm2java
 */
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler" })
@Embeddable
public class SysRolePermissionId implements java.io.Serializable {

	private int roleId;
	private int menuId;
	private int menuClassId;

	public SysRolePermissionId() {
	}

	public SysRolePermissionId(int roleId, int menuId, int menuClassId) {
		this.roleId = roleId;
		this.menuId = menuId;
		this.menuClassId = menuClassId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "menu_id", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "menu_class_id", nullable = false)
	public int getMenuClassId() {
		return this.menuClassId;
	}

	public void setMenuClassId(int menuClassId) {
		this.menuClassId = menuClassId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SysRolePermissionId))
			return false;
		SysRolePermissionId castOther = (SysRolePermissionId) other;

		return (this.getRoleId() == castOther.getRoleId()) && (this.getMenuId() == castOther.getMenuId())
				&& (this.getMenuClassId() == castOther.getMenuClassId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getMenuId();
		result = 37 * result + this.getMenuClassId();
		return result;
	}

}
