package com.framework.entity;

// Generated 2017-5-26 22:41:39 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysRolePermission generated by hbm2java
 */
@Entity
@Table(name = "sys_role_permission", catalog = "wx")
public class SysRolePermission implements java.io.Serializable {

	private int roleId;
	private int menuId;
	private int menuClassId;

	@Id
	@Column(name = "role_id", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "menu_id", nullable = false)
	public int getMenuId() {
		return this.menuId;
	}

	public void setMenuId(int menuId) {
		this.menuId = menuId;
	}

	@Column(name = "menu_class_id", nullable = false)
	public int getMenuClassId() {
		return this.menuClassId;
	}

	public void setMenuClassId(int menuClassId) {
		this.menuClassId = menuClassId;
	}

}
